CREATE TABLE customers (
                           customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           full_name VARCHAR(100) NOT NULL,
                           email VARCHAR(100) NOT NULL UNIQUE,
                           phone VARCHAR(30) NOT NULL,
                           license_number VARCHAR(50) NOT NULL,
                           license_expiry_date DATE NOT NULL,
                           eligible_to_rent BOOLEAN NOT NULL
);

CREATE TABLE vehicles (
                          vehicle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          brand VARCHAR(50) NOT NULL,
                          model VARCHAR(50) NOT NULL,
                          vehicle_year INT NOT NULL,
                          plate_number VARCHAR(20) NOT NULL UNIQUE,
                          status VARCHAR(30) NOT NULL,
                          daily_rate DECIMAL(10,2) NOT NULL
);

CREATE TABLE invoices (
                          invoice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          rental_id BIGINT,
                          amount DECIMAL(10,2) NOT NULL,
                          payment_status VARCHAR(30) NOT NULL,
                          payment_date DATE
);

CREATE TABLE rentals (
                         rental_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         customer_id BIGINT NOT NULL,
                         vehicle_id BIGINT NOT NULL,
                         invoice_id BIGINT,
                         start_date DATE NOT NULL,
                         end_date DATE NOT NULL,
                         status VARCHAR(30) NOT NULL,
                         CONSTRAINT fk_rental_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
                         CONSTRAINT fk_rental_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(vehicle_id),
                         CONSTRAINT fk_rental_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(invoice_id)
);

INSERT INTO customers (full_name, email, phone, license_number, license_expiry_date, eligible_to_rent) VALUES
                                                                                                           ('John Smith', 'john@example.com', '5141111111', 'LIC12345', DATE '2028-12-31', TRUE),
                                                                                                           ('Sara Lee', 'sara@example.com', '5142222222', 'LIC67890', DATE '2027-06-30', TRUE),
                                                                                                           ('Mike Brown', 'mike@example.com', '5143333333', 'LIC99999', DATE '2026-08-15', TRUE),
                                                                                                           ('Emma Wilson', 'emma@example.com', '5144444444', 'LIC77777', DATE '2029-01-01', TRUE),
                                                                                                           ('David Clark', 'david@example.com', '5145555555', 'LIC88888', DATE '2025-12-20', FALSE);

INSERT INTO vehicles (brand, model, vehicle_year, plate_number, status, daily_rate) VALUES
                                                                                        ('Toyota', 'Corolla', 2022, 'ABC123', 'AVAILABLE', 55.00),
                                                                                        ('Honda', 'Civic', 2023, 'XYZ789', 'AVAILABLE', 65.00),
                                                                                        ('Ford', 'Escape', 2021, 'DEF456', 'RENTED', 70.00),
                                                                                        ('BMW', 'X5', 2024, 'GHI321', 'AVAILABLE', 120.00),
                                                                                        ('Tesla', 'Model 3', 2023, 'TES123', 'AVAILABLE', 150.00);

INSERT INTO invoices (rental_id, amount, payment_status, payment_date) VALUES
                                                                           (NULL, 120.00, 'PENDING', NULL),
                                                                           (NULL, 200.00, 'PAID', DATE '2024-05-01'),
                                                                           (NULL, 300.00, 'PAID', DATE '2024-06-10');

INSERT INTO rentals (customer_id, vehicle_id, invoice_id, start_date, end_date, status) VALUES
                                                                                            (1, 1, 1, DATE '2024-07-01', DATE '2024-07-05', 'ACTIVE'),
                                                                                            (2, 2, 2, DATE '2024-06-01', DATE '2024-06-03', 'COMPLETED'),
                                                                                            (3, 3, 3, DATE '2024-05-10', DATE '2024-05-15', 'COMPLETED');